version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./src/data/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql"
      - "./src/data/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql"
    ports:
      - "3306:3306"